name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  # Variable Above comes from wgpu ci
  VULKAN_SDK_VERSION: "1.3.290"
  MESA_VERSION: "24.2.3"
  # Corresponds to https://github.com/gfx-rs/ci-build/releases
  CI_BINARY_BUILD: "build19"

jobs:
  # Run cargo test on Linux
  test-linux:
    name: Test Suite on Linux AMD64 Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.2
      - run: |
          rustup component add rustc-codegen-cranelift-preview --toolchain nightly

  test-macos:
    name: Test Suite on MacOS
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.2
      - run: |
          rustup component add rustc-codegen-cranelift-preview --toolchain nightly
      - name: Run cargo test
        run: |
          cargo test

  # Run cargo clippy -- -D warnings
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: |
          rustup component add rustc-codegen-cranelift-preview --toolchain nightly
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.2
      - name: Install Dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install --no-install-recommends pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev clang mold libwayland-dev libxkbcommon-dev;
      - name: Run clippy
        run: cargo clippy -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: |
          rustup component add rustc-codegen-cranelift-preview --toolchain nightly
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
